return {
  fields = {
    api_endpoint = {required = true, type = "url", default = "https://api.moesif.net"},
    timeout = {default = 1000, type = "number"},
    connect_timeout = {default = 1000, type = "number"},
    send_timeout = {default = 2000, type = "number"},
    keepalive = {default = 5000, type = "number"},
    event_queue_size = {default = 1000, type = "number"},
    api_version = {default = "1.0", type = "string"},
    application_id = {required = true, default ="", type="string"},
    disable_capture_request_body = {default = false, type = "boolean"},
    disable_capture_response_body = {default = false, type = "boolean"},
    request_masks = {default = {}, type = "array"},
    request_body_masks = {default = {}, type = "array"},
    request_header_masks = {default = {}, type = "array"},
    response_masks = {default = {}, type = "array"},
    response_body_masks = {default = {}, type = "array"},
    response_header_masks = {default = {}, type = "array"},
    batch_size = {default = 200, type = "number"},
    disable_transaction_id = {default = false, type = "boolean"},
    debug = {default = false, type = "boolean"},
    disable_gzip_payload_decompression = {default = false, type = "boolean"},
    user_id_header = {default = "", type = "string"},
    company_id_header = {default = "", type = "string"},
    max_callback_time_spent = {default = 2000, type = "number"},
    max_body_size_limit = {default = 500000, type = "number"},
  }
}
